// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpD_3BhsthqrrU-9kjTg5uo8HoKGB34fU',
    appId: '1:217095734613:android:72594861525a630bd85bdc',
    messagingSenderId: '217095734613',
    projectId: 'gstproject-9b3bb',
    storageBucket: 'gstproject-9b3bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwzjKJDL-D12imIaEVJLTf53crYWh4f78',
    appId: '1:217095734613:ios:831e68bb720fb721d85bdc',
    messagingSenderId: '217095734613',
    projectId: 'gstproject-9b3bb',
    storageBucket: 'gstproject-9b3bb.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsGW3K_UUd43UBGxm_G007dlHKv5L7TQ',
    appId: '1:217095734613:web:6a14bdaab349ccb9d85bdc',
    messagingSenderId: '217095734613',
    projectId: 'gstproject-9b3bb',
    authDomain: 'gstproject-9b3bb.firebaseapp.com',
    storageBucket: 'gstproject-9b3bb.firebasestorage.app',
    measurementId: 'G-6JH7P05WX1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwzjKJDL-D12imIaEVJLTf53crYWh4f78',
    appId: '1:217095734613:ios:831e68bb720fb721d85bdc',
    messagingSenderId: '217095734613',
    projectId: 'gstproject-9b3bb',
    storageBucket: 'gstproject-9b3bb.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzsGW3K_UUd43UBGxm_G007dlHKv5L7TQ',
    appId: '1:217095734613:web:888c093c2a81920fd85bdc',
    messagingSenderId: '217095734613',
    projectId: 'gstproject-9b3bb',
    authDomain: 'gstproject-9b3bb.firebaseapp.com',
    storageBucket: 'gstproject-9b3bb.firebasestorage.app',
    measurementId: 'G-TFMYEVP05P',
  );

}